package com.bigdata.olearn.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMoocCluster<M extends BaseMoocCluster<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public BigInteger getId() {
		return get("id");
	}

	public void setClassname(String classname) {
		set("classname", classname);
	}

	public String getClassname() {
		return get("classname");
	}

	public void setPrelabel(String prelabel) {
		set("prelabel", prelabel);
	}

	public String getPrelabel() {
		return get("prelabel");
	}

	public void setFieldId(BigInteger fieldId) {
		set("field_id", fieldId);
	}

	public BigInteger getFieldId() {
		return get("field_id");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
