package com.bigdata.olearn.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWork<M extends BaseWork<M>> extends Model<M> implements IBean {

	public void setWorkId(BigInteger workId) {
		set("work_id", workId);
	}

	public BigInteger getWorkId() {
		return get("work_id");
	}

	public void setWorkname(String workname) {
		set("workname", workname);
	}

	public String getWorkname() {
		return get("workname");
	}

	public void setClusterId(BigInteger clusterId) {
		set("cluster_id", clusterId);
	}

	public BigInteger getClusterId() {
		return get("cluster_id");
	}

	public void setClassname(String classname) {
		set("classname", classname);
	}

	public String getClassname() {
		return get("classname");
	}

	public void setLink(String link) {
		set("link", link);
	}

	public String getLink() {
		return get("link");
	}

	public void setSaray(String saray) {
		set("saray", saray);
	}

	public String getSaray() {
		return get("saray");
	}

	public void setLocation(String location) {
		set("location", location);
	}

	public String getLocation() {
		return get("location");
	}

	public void setLocationDetail(String locationDetail) {
		set("location_detail", locationDetail);
	}

	public String getLocationDetail() {
		return get("location_detail");
	}

	public void setExperience(String experience) {
		set("experience", experience);
	}

	public String getExperience() {
		return get("experience");
	}

	public void setEducation(String education) {
		set("education", education);
	}

	public String getEducation() {
		return get("education");
	}

	public void setCompany(String company) {
		set("company", company);
	}

	public String getCompany() {
		return get("company");
	}

	public void setIntroduce(String introduce) {
		set("introduce", introduce);
	}

	public String getIntroduce() {
		return get("introduce");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
