package com.bigdata.olearn.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMoocMenu<M extends BaseMoocMenu<M>> extends Model<M> implements IBean {

	public void setId(BigInteger id) {
		set("id", id);
	}

	public BigInteger getId() {
		return get("id");
	}

	public void setMoocId(BigInteger moocId) {
		set("mooc_id", moocId);
	}

	public BigInteger getMoocId() {
		return get("mooc_id");
	}

	public void setLesson(String lesson) {
		set("lesson", lesson);
	}

	public String getLesson() {
		return get("lesson");
	}

	public void setSequence(Integer sequence) {
		set("sequence", sequence);
	}

	public Integer getSequence() {
		return get("sequence");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
