spring:
  data:
    neo4j:
      uri: bolt://47.107.150.100:7687
      username: neo4j
      password: asdfgh



jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://47.107.150.100:3306/bigdata?characterEncoding=utf8&serverTimezone=UTC
  dbUser: root
  dbPwd: wxm19980928