spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: asdfgh



jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://120.79.79.141:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC
  dbUser: root
  dbPwd: 123456