package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseAbility;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ability extends BaseAbility<Ability> {
    public static final Ability dao = new Ability().dao();
}