package com.bigdata.olearn.model;


import com.bigdata.olearn.model.base.BaseField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Field extends BaseField<Field> {
    public static final Field dao = new Field().dao();
}