package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseMoocCluster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MoocCluster extends BaseMoocCluster<MoocCluster> {
	public static final MoocCluster dao = new MoocCluster().dao();
}
