package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseMooc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mooc extends BaseMooc<Mooc> {
	public static final Mooc dao = new Mooc().dao();
}
