package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseMoocMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MoocMenu extends BaseMoocMenu<MoocMenu> {
	public static final MoocMenu dao = new MoocMenu().dao();
}
