package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseMoocLinkCluster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MoocLinkCluster extends BaseMoocLinkCluster<MoocLinkCluster> {
	public static final MoocLinkCluster dao = new MoocLinkCluster().dao();
}
