package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Schedule extends BaseSchedule<Schedule> {
	public static final Schedule dao = new Schedule().dao();
}
