package com.bigdata.olearn.model;


import com.bigdata.olearn.model.base.BaseUserLinkField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLinkField extends BaseUserLinkField<UserLinkField> {
    public static final UserLinkField dao = new UserLinkField().dao();
}
