package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Work extends BaseWork<Work> {
	public static final Work dao = new Work().dao();
}
