package com.bigdata.olearn.model;

import com.bigdata.olearn.model.base.BaseWorkCluster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkCluster extends BaseWorkCluster<WorkCluster> {
	public static final WorkCluster dao = new WorkCluster().dao();
}
